### ISSUE TITLE
[PYTHON] - Alterar coluna rascunho da tabela tombos

### ISSUE THREAD

**Issue by ncs92** [utfpr/hcf-web#31]
Alterar o script para para que a coluna rascunho seja inserida com o valor 0 na tabela de tombos

**Comment by RyanRamos01** [comment]
![image](https://github.com/utfpr/hcf-web/assets/49281976/ace1d9b1-5ce8-4ae4-a999-c018693a5937)

Feito e foi commitado no pr da branch 27-adaptar-script-de-conversão-para-armazenar-identificadores.
