### ISSUE TITLE
[Infra] Validar e corrigir duplicação de dados durante a migração

### ISSUE THREAD

**Issue by edvaldoszy** [utfpr/hcf-web#34]
Algumas tabelas estão com informações duplicadas. Cabe a você investigar primeiramente se há um problema durante a migração dos dados ou se as informações já estão duplicadas no banco atual (GDB).

Caso os dados estejam duplicados no banco atual (GDB), uma opção válida é levar a questão para o Marcelo Caxambu e verificar se é algum funcionamento previso ou algum problema que pode ser consertado.

Veja abaixo a lista de tabelas com informações duplicadas:

- generos
- especies
- subespecies
- autores
- coletores
- variedades

**generos**

![Image](https://github.com/utfpr/hcf-web/assets/3211168/13347434-100a-41f6-b110-48c37372aed8)

**especies**

![Image](https://github.com/utfpr/hcf-web/assets/3211168/2d5d40a2-31e1-433f-a8bd-70f08f92e9df)

**subespecies**

![Image](https://github.com/utfpr/hcf-web/assets/3211168/7f6f849d-bfbb-4012-a2bf-165ab38da971)

**autores**

![Image](https://github.com/utfpr/hcf-web/assets/3211168/f8ee6932-2660-4698-8ff4-2cf575d62769)

**coletores**

![Image](https://github.com/utfpr/hcf-web/assets/3211168/1dedb6a8-8fb6-4601-abe1-595388f3183d)

**variedades**

![Image](https://github.com/utfpr/hcf-web/assets/3211168/c4393b2c-0b0e-4622-88a3-af25555a8b24)

---

Você pode utilizar o SQL abaixo para verificar quais nomes estão duplicados, modificando o nome da tabela para a qual deseja validar:

```sql
select nome, count(1) from <table name>
group by nome
having count(1) > 1
```

**Comment by RyanRamos01** [comment]
Acho que teremos que verificar com o Caxambu, verifiquei no GDB esses dados possívelmente duplicados e eles estão lá, não é nenhum comportamento do script. Segue todos os conteúdos verificados:

Generos:

![Image](https://github.com/utfpr/hcf-web/assets/49281976/8d2f8875-8700-4a81-bbbd-e3f41db57454)

Especies:

![Image](https://github.com/utfpr/hcf-web/assets/49281976/21e659b2-7abe-49c6-9aba-70cc036b2778)

Sub_especies:

![Image](https://github.com/utfpr/hcf-web/assets/49281976/f3626d44-e59c-48b5-94d7-1133d886c5a6)

Autores:

![Image](https://github.com/utfpr/hcf-web/assets/49281976/b4d40444-6f86-4ebb-ad75-87a1cc87acf3)

Coletores:

![Image](https://github.com/utfpr/hcf-web/assets/49281976/45c8ab48-e65d-4892-a2be-9bdbb5b1ca8c)

Variedades:

![Image](https://github.com/utfpr/hcf-web/assets/49281976/4f157582-36a6-4983-a424-e7475ceb89df)
